### ISSUE TITLE
Fails to init DIR on Arch linux

### ISSUE THREAD

**Issue by jmarcet** [doudou/snapsync#14]
`[13:42:32] root :: xps9570  ➜  /storage/backups/xps9570 » snapsync init arch /storage/backups/xps9570                                                                                                                                                                    130 ↵
 INFO  Snapsync : initialized /storage/backups/xps9570/log as a snapsync target
 INFO  Snapsync : initialized /storage/backups/xps9570/home as a snapsync target
 INFO  Snapsync : initialized /storage/backups/xps9570/local as a snapsync target
 INFO  Snapsync : initialized /storage/backups/xps9570/root as a snapsync target
 INFO  Snapsync : initialized /storage/backups/xps9570/opt as a snapsync target
/usr/lib/ruby/gems/2.6.0/gems/ruby-dbus-0.11.0/lib/dbus/marshall.rb:301: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/gems/2.6.0/gems/ruby-dbus-0.11.0/lib/dbus/message.rb:129: warning: constant ::Fixnum is deprecated
Traceback (most recent call last):
        10: from /usr/bin/snapsync:23:in `<main>'
         9: from /usr/bin/snapsync:23:in `load'
         8: from /usr/lib/ruby/gems/2.6.0/gems/snapsync-0.3.0/bin/snapsync:4:in `<top (required)>'
         7: from /root/.gem/ruby/2.6.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
         6: from /root/.gem/ruby/2.6.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
         5: from /root/.gem/ruby/2.6.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
         4: from /root/.gem/ruby/2.6.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
         3: from /usr/lib/ruby/gems/2.6.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:141:in `init'
         2: from /usr/lib/ruby/gems/2.6.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:169:in `auto_add'
         1: from /usr/lib/ruby/gems/2.6.0/gems/snapsync-0.3.0/lib/snapsync/auto_sync.rb:137:in `add'
/usr/lib/ruby/gems/2.6.0/gems/snapsync-0.3.0/lib/snapsync/partitions_monitor.rb:28:in `monitor_for': undefined method `to_str' for nil:NilClass (NoMethodError)
[`

**Comment by doudou** [comment]
Hi Javier

I'm not using snapsync anymore, so not maintaining it either. If you feel like taking over, I'll gladly pass it on to you.

See https://github.com/doudou/snapsync/issues/13 more some more information about why
