### ISSUE TITLE
snapsync fails without `/etc/snapsync.conf` and undefined method `to_str' 

### ISSUE THREAD

**Issue by jchnkl** [doudou/snapsync#3]
Hi,

snapsync fails on my machine with these errors:

```
/usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/auto_sync.rb:29:in `read': No such file or directory @ rb_sysopen - /etc/snapsync.conf (Errno::ENOENT)
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/auto_sync.rb:29:in `read'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/auto_sync.rb:29:in `load_config'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:156:in `auto_add'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:141:in `init'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/bin/snapsync:4:in `<top (required)>'
        from /usr/bin/snapsync:23:in `load'
        from /usr/bin/snapsync:23:in `<main>'
```

after `touch /etc/snapsync.conf`:

```
/usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/partitions_monitor.rb:28:in `monitor_for': undefined method `to_str' for nil:NilClass (NoMethodError)
Did you mean?  to_s
               to_r
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/auto_sync.rb:137:in `add'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:169:in `auto_add'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/lib/snapsync/cli.rb:141:in `init'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib/ruby/gems/2.3.0/gems/snapsync-0.3.0/bin/snapsync:4:in `<top (required)>'
        from /usr/bin/snapsync:23:in `load'
        from /usr/bin/snapsync:23:in `<main>'
```

Here are the gem versions I've installed:

```
ruby 2.3.0-1
ruby-concurrent-ruby-0 0.9.2-1
ruby-logging 2.0.0-1
ruby-ruby-dbus 0.11.0-1
ruby-thor 0.19.1-1
```

FWIW this is an Arch Linux system and I just used the `gem2arch` util to
generate the packages.

**Comment by doudou** [comment]
Should be fixed by 0.3.1 (that I just released). Thanks for reporting.
